"""
Test Suite
"""


# ALL comments in:
#   tests
    # ├── __init__.py
    # ├── test_batch_downloader.py
    # ├── test_channel_scraper.py
    # ├── test_gui.py
    # ├── test_mp3_converter.py
    # ├── test_mp4_converter.py
    # └── test_playlist_scraper.py
#----------------------------------------------------------------
#  were generated by AI so they might not be 100% accurate.