"""
TubeHarvester - YouTube Downloader Package

This package provides functionality for downloading YouTube videos and playlists
in various formats (MP3, MP4) with both GUI and programmatic interfaces.
"""

__version__ = "1.0.0"
__author__ = "Panagopoulos Nikolaos"


# ALL comments in:
# 
# 
# ├── main.py
# ├── run_tests.py
# ├── src
# │   ├── BatchDownloader.py
# │   ├── ChannelScraper.py
# │   ├── GUI.py
# │   ├── __init__.py
# │   ├── Mp3_Converter.py
# │   ├── Mp4_Converter.py
# │   ├── PlaylistScraper.py
# ----------------------------------------------------------------
#  were generated by AI so they might not be 100% accurate.